services:
  database:
    build:
      context: ./database
      dockerfile: Dockerfile
    image: "messagecollector-database"
    container_name: "messagecollector-database"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=messagecollector
    ports:
      - "5432:5432"
    networks:
      - intra
    restart: always
  collector:
    build:
      context: ./collector
      dockerfile: Dockerfile
    image: "messagecollector-collector"
    container_name: "messagecollector-collector"
    environment:
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_CONTAINER_NAME=messagecollector-database
      - DB_NAME=messagecollector
      - DB_PORT=5432
    depends_on:
      - database
    ports:
      - "8080:8080"
    networks:
      - intra
    restart: always
  statprovider:
    build:
      context: ./statprovider
      dockerfile: Dockerfile
    image: "messagecollector-statprovider"
    container_name: "messagecollector-statprovider"
    environment:
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_CONTAINER_NAME=messagecollector-database
      - DB_NAME=messagecollector
      - DB_PORT=5432
    depends_on:
      - database
      - collector
    ports:
      - "8081:8081"
    networks:
      - intra
    restart: always
networks:
  intra:

